package apcs.unit09.FantasyFootball;

import java.util.Scanner;
import java.io.*;
import java.util.ArrayList;
import java.util.Arrays;

public class dataParser {
    public static void main(String[] args) {
        String[] playerNames = {
                "Aaron Rodgers",
                "Matthew Stafford",
                "Randall Cobb",
                "Tyrod Taylor",
                "Russell Wilson",
                "Marvin Jones",
                "Kirk Cousins",
                "Ryan Tannehill",
                "Adam Thielen",
                "Zach Ertz",
                "Marquise Goodwin",
                "Keenan Allen",
                "Robert Woods",
                "Latavius Murray",
                "DeAndre Hopkins",
                "Geno Smith",
                "Odell Beckham",
                "Brandin Cooks",
                "Logan Thomas",
                "Derek Carr",
                "Jimmy Garoppolo",
                "Jerick McKinnon",
                "Davante Adams",
                "Mike Evans",
                "Allen Robinson",
                "Amari Cooper",
                "Stefon Diggs",
                "Michael Burton",
                "Darren Waller",
                "Raheem Mostert",
                "DeAndre Carter",
                "Blake Bell",
                "Ameer Abdullah",
                "Ty Montgomery",
                "Phillip Dorsett",
                "Tyler Lockett",
                "Sterling Shepard",
                "Austin Hooper",
                "Chris Moore",
                "Kalif Raymond",
                "Derrick Henry",
                "Michael Thomas",
                "C.J. Ham",
                "Tyler Boyd",
                "Tyreek Hill",
                "Ezekiel Elliott",
                "Dak Prescott",
                "Hunter Henry",
                "Jared Goff",
                "Tyler Higbee",
                "Mo Alie-Cox",
                "Zach Pascal",
                "Christian McCaffrey",
                "Curtis Samuel",
                "George Kittle",
                "Aaron Jones",
                "Kendrick Bourne",
                "Matt Breida",
                "Taysom Hill",
                "Samaje Perine",
                "Mike Williams",
                "Deshaun Watson",
                "James Conner",
                "Mack Hollins",
                "Jamal Agnew",
                "Noah Brown",
                "Cooper Rush",
                "Austin Ekeler",
                "JuJu Smith-Schuster",
                "Patrick Mahomes",
                "Evan Engram",
                "David Njoku",
                "Zay Jones",
                "Dalvin Cook",
                "Gerald Everett",
                "Joe Mixon",
                "Chris Godwin",
                "D'Onta Foreman",
                "Josh Reynolds",
                "Jamaal Williams",
                "Joshua Dobbs",
                "River Cracraft",
                "Will Dissly",
                "Gus Edwards",
                "Mike Boone",
                "Tyler Conklin",
                "Marquez Valdes-Scantling",
                "Richie James",
                "Keith Kirkwood",
                "Courtland Sutton",
                "Dallas Goedert",
                "Jordan Akins",
                "Dalton Schultz",
                "Justin Watson",
                "Boston Scott",
                "Braxton Berrios",
                "Allen Lazard",
                "Chase Edmonds",
                "Michael Gallup",
                "Christian Kirk",
                "Nick Chubb",
                "Lamar Jackson",
                "Durham Smythe",
                "D.J. Moore",
                "Mike Gesicki",
                "Hayden Hurst",
                "Calvin Ridley",
                "Saquon Barkley",
                "Baker Mayfield",
                "Josh Allen",
                "Sam Darnold",
                "Jakobi Meyers",
                "Irv Smith",
                "Alexander Mattison",
                "Justice Hill",
                "Khari Blasingame",
                "Jake Browning",
                "Alec Ingold",
                "Deonte Harty",
                "Diontae Johnson",
                "T.J. Hockenson",
                "Miles Sanders",
                "Josh Oliver",
                "Devin Singletary",
                "Tony Pollard",
                "Gardner Minshew",
                "Trayveon Williams",
                "Donald Parham",
                "Lil'Jordan Humphrey",
                "Darius Slayton",
                "D'Ernest Johnson",
                "Parris Campbell",
                "DK Metcalf",
                "Damien Harris",
                "Terry McLaurin",
                "Marquise Brown",
                "A.J. Brown",
                "David Montgomery",
                "Dawson Knox",
                "Josh Jacobs",
                "Daniel Jones",
                "Deebo Samuel",
                "Tony Jones",
                "Giovanni Ricci",
                "Patrick Taylor",
                "Salvon Ahmed",
                "Juwan Johnson",
                "Rico Dowdle",
                "Lawrence Cager",
                "J.K. Dobbins",
                "Isaiah Hodgins",
                "Nick Westbrook-Ikhine",
                "Gabe Davis",
                "Tua Tagovailoa",
                "Harrison Bryant",
                "Donovan Peoples-Jones",
                "Colby Parkinson",
                "Michael Pittman",
                "Jauan Jennings",
                "Brandon Aiyuk",
                "Jordan Love",
                "A.J. Dillon",
                "Laviska Shenault",
                "Quez Watkins",
                "D'Andre Swift",
                "Cole Kmet",
                "Darnell Mooney",
                "Justin Jefferson",
                "Chase Claypool",
                "Antonio Gibson",
                "Anthony McFarland",
                "K.J. Osborn",
                "Justin Herbert",
                "CeeDee Lamb",
                "Clyde Edwards-Helaire",
                "Joshua Kelley",
                "Jalen Hurts",
                "Tee Higgins",
                "Cam Akers",
                "Van Jefferson",
                "Adam Trautman",
                "Brycen Hopkins",
                "DeeJay Dallas",
                "Joe Burrow",
                "Deon Jackson",
                "Rashod Bateman",
                "Nico Collins",
                "Chuba Hubbard",
                "Elijah Mitchell",
                "Gary Brightwell",
                "Jaylen Waddle",
                "Noah Gray",
                "Brock Wright",
                "Tutu Atwell",
                "Chris Evans",
                "Jake Funk",
                "Ben Skowronek",
                "Rhamondre Stevenson",
                "Kylen Granson",
                "Najee Harris",
                "Pat Freiermuth",
                "Ja'Marr Chase",
                "Khalil Herbert",
                "DeVonta Smith",
                "Kadarius Toney",
                "Kenneth Gainwell",
                "Michael Carter",
                "Rondale Moore",
                "Justin Fields",
                "Terrace Marshall",
                "Amon-Ra St. Brown",
                "Kyle Pitts",
                "Trevor Lawrence",
                "Mac Jones",
                "Travis Etienne",
                "Elijah Moore",
                "Josh Palmer",
                "Javonte Williams",
                "Zach Wilson",
                "Sam Howell",
                "Cole Turner",
                "Samori Toure",
                "Isiah Pacheco",
                "Justyn Ross",
                "Jaylen Warren",
                "Drake London",
                "Chris Olave",
                "George Pickens",
                "James Cook",
                "Greg Dulcich",
                "Rachaad White",
                "David Bell",
                "Dameon Pierce",
                "Tyler Allgeier",
                "Jerome Ford",
                "Ty Chandler",
                "Teagan Quitoriano",
                "Andrew Ogletree",
                "Keaontay Ingram",
                "Connor Heyward",
                "Ko Kieft",
                "Brandon Johnson",
                "Deven Thompkins",
                "Rashid Shaheed",
                "Peyton Hendershot",
                "Alec Pierce",
                "Jalen Tolbert",
                "Garrett Wilson",
                "Jahan Dotson",
                "Treylon Burks",
                "Trey McBride",
                "Brian Robinson",
                "Kavontae Turpin",
                "Chigoziem Okonkwo",
                "Romeo Doubs",
                "Brock Purdy",
                "Calvin Austin",
                "Isaiah Likely",
                "Kyren Williams",
                "Zamir White",
                "Jake Ferguson",
                "Charlie Kolar",
                "Skyy Moore",
                "Erik Ezukanma",
                "Kenny Pickett",
                "Daniel Bellinger",
                "Breece Hall",
                "Desmond Ridder",
                "Cade Otton",
                "Kenneth Walker",
                "Sean Clifford",
                "Dontayvion Wicks",
                "Evan Hull",
                "Malik Heath",
                "Xavier Gipson",
                "Bijan Robinson",
                "Jaxon Smith-Njigba",
                "Quentin Johnston",
                "Tank Bigsby",
                "Michael Wilson",
                "Derius Davis",
                "Kayshon Boutte",
                "Chris Rodriguez",
                "Xavier Hutchinson",
                "Demario Douglas",
                "Deuce Vaughn",
                "Jaleel McLaughlin",
                "Rakim Jarrett",
                "Dalton Kincaid",
                "Jalin Hyatt",
                "Tyler Scott",
                "Sean Tucker",
                "Marvin Mims",
                "Nathaniel Dell",
                "Jordan Addison",
                "Josh Downs",
                "Roschon Johnson",
                "Tyjae Spears",
                "Trey Palmer",
                "Jonathan Mingo",
                "Zay Flowers",
                "Sam LaPorta",
                "Rashee Rice",
                "Puka Nacua",
                "Jahmyr Gibbs",
                "Luke Musgrave",
                "Jayden Reed",
                "Bryce Young",
                "C.J. Stroud",
                "Anthony Richardson",
                "Zach Charbonnet"
        };
        String[] positions = {
                "QB", "QB", "WR", "QB", "QB", "WR", "QB", "QB", "WR", "TE",
                "WR", "WR", "WR", "RB", "WR", "QB", "WR", "WR", "TE", "QB",
                "QB", "RB", "WR", "WR", "WR", "WR", "WR", "RB", "TE", "RB",
                "WR", "TE", "RB", "WR", "WR", "WR", "WR", "TE", "WR", "WR",
                "RB", "WR", "RB", "WR", "WR", "RB", "QB", "TE", "QB", "TE",
                "TE", "WR", "RB", "WR", "TE", "RB", "WR", "RB", "QB", "RB",
                "WR", "QB", "RB", "WR", "WR", "WR", "QB", "RB", "WR", "QB",
                "TE", "TE", "WR", "RB", "TE", "RB", "WR", "RB", "WR", "RB",
                "QB", "WR", "TE", "RB", "RB", "TE", "WR", "WR", "WR", "WR",
                "TE", "TE", "TE", "WR", "RB", "WR", "WR", "RB", "WR", "WR",
                "RB", "QB", "TE", "WR", "TE", "TE", "WR", "RB", "QB", "QB",
                "QB", "WR", "TE", "RB", "RB", "RB", "QB", "RB", "WR", "WR",
                "TE", "RB", "TE", "RB", "RB", "QB", "RB", "TE", "WR", "WR",
                "RB", "WR", "WR", "RB", "WR", "WR", "WR", "RB", "TE", "RB",
                "QB", "WR", "RB", "TE", "RB", "RB", "TE", "RB", "TE", "RB",
                "WR", "WR", "WR", "QB", "TE", "WR", "TE", "WR", "WR", "WR",
                "QB", "RB", "WR", "WR", "RB", "TE", "WR", "WR", "WR", "RB",
                "RB", "WR", "QB", "WR", "RB", "RB", "QB", "WR", "RB", "WR",
                "TE", "TE", "RB", "QB", "RB", "WR", "WR", "RB", "RB", "RB",
                "WR", "TE", "TE", "WR", "RB", "RB", "WR", "RB", "TE", "RB",
                "TE", "WR", "RB", "WR", "WR", "RB", "RB", "WR", "QB", "WR",
                "WR", "TE", "QB", "QB", "RB", "WR", "WR", "RB", "QB", "QB",
                "TE", "WR", "RB", "WR", "RB", "WR", "WR", "WR", "RB", "TE",
                "RB", "WR", "RB", "RB", "RB", "RB", "TE", "TE", "RB", "TE",
                "TE", "WR", "WR", "WR", "TE", "WR", "WR", "WR", "WR", "WR",
                "TE", "RB", "WR", "TE", "WR", "QB", "WR", "TE", "RB", "RB",
                "TE", "TE", "WR", "WR", "QB", "TE", "RB", "QB", "TE", "RB",
                "QB", "WR", "RB", "WR", "WR", "RB", "WR", "WR", "RB", "WR",
                "WR", "WR", "RB", "WR", "WR", "RB", "RB", "WR", "TE", "WR",
                "WR", "RB", "WR", "WR", "WR", "WR", "RB", "RB", "WR", "WR",
                "WR", "TE", "WR", "WR", "RB", "TE", "WR", "QB", "QB", "QB",
                "RB"
        };
        int[] passingYards = {
                0, 334, 0, 6, 177, 0, 344, 198, 0, 0, 0, 0, 0, 0, 0, 112, 0, 0, 0, 305,
                200, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 143, 0, 253, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 154, 0, 0, 0, 0,
                0, 0, 0, 226, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 132, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 169, 0, 0, 0, 0, 0, 0, 173, 236, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 104, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 466, 0, 0, 0, 0,
                0, 0, 245, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 229, 0, 0, 0, 170, 0, 0, 0,
                0, 0, 0, 82, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 216, 0, 0, 0, 241, 316, 0, 0, 0, 0, 140, 202, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 220, 0, 0, 0, 0, 0, 0, 0, 0, 232, 0, 0, 115, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 146, 242, 223, 0
        };
        int[] passingTD = {
                0, 0, 0, 0, 2, 0, 2, 0, 0, 0,
                0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
                2, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 1, 0, 0, 0, 0, 0, 0, 0, 2,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 2, 1,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 3, 0, 0, 0, 0, 0, 0,
                3, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
                0, 0, 2, 3, 0, 0, 0, 0, 1, 1,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 2, 0, 0, 0, 0,
                0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
                0
        };
        int[] rushYards = {
                0, 11, 0, 0, 1, 0, 7, 5, 0, 0,
                0, 6, 0, 8, 0, 6, 0, 0, 0, 4,
                11, 0, 0, 0, 0, 0, 0, 0, 0, 37,
                0, 0, 0, 7, 0, 0, 0, 0, 0, 0,
                63, 0, 0, 0, 0, 29, 6, 0, -1, 0,
                0, 0, 152, 6, 0, 41, 0, 9, 4, 41,
                0, 45, 62, 0, -2, -1, 0, 117, 0, 45,
                0, 0, 0, 33, 2, 56, 0, 16, 0, 45,
                -3, 0, 0, 32, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 3, 0, 0, 8, 0, 0,
                106, 38, 0, 0, 0, 0, 0, 51, 11, 36,
                -2, 0, 0, 34, 9, 0, -1, 0, 4, 0,
                0, 72, 0, 15, 70, 0, 7, 0, 0, 0,
                -4, 0, 0, 3, 0, 29, 0, 74, 0, 48,
                43, 8, 5, 0, 22, 11, 0, 24, 0, 22,
                0, 0, 0, 5, 0, 0, 0, 0, 0, 0,
                12, 19, 5, 0, 3, 0, 0, 0, 0, 9,
                0, 0, 17, 0, 22, 91, 37, 0, 29, 0,
                0, 0, 4, -1, 14, 0, 0, 60, 10, 5,
                0, 0, 0, 0, 12, 10, 0, 25, 0, 31,
                0, 2, 27, 0, -1, 54, 6, 12, 59, 0,
                0, 0, 21, 15, 77, 19, 0, 52, 6, 11,
                0, 0, 23, 0, 6, 0, 0, 0, 46, 0,
                39, 0, 38, 75, 36, 0, 0, 0, -4, 0,
                0, 0, 0, 11, 0, 0, 0, 0, 0, 9,
                0, 59, 14, 0, 0, 20, 0, 0, 52, 2,
                0, 0, 4, 17, 4, 0, 127, -1, 0, 64,
                0, 0, 1, 0, 0, 56, 0, 0, 13, 0,
                0, 0, 7, 0, 0, 8, 0, 0, 0, 0,
                0, 15, 0, 0, 0, 0, 20, 27, 0, 0,
                9, 0, -3, 0, 42, 0, -2, 17, 20, 40,
                11
        };
        int[] rushTD = {
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
                0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 2, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 2, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 2, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 1, 0, 0, 0, 0, 0, 2, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
                0
        };
        int[] RecYards = {
                0, 0, 0, 0, 0, 8, 0, 0, 12, 21,
                0, 76, 57, 9, 65, 0, 37, 22, 43, 0,
                0, 10, 66, 66, 64, 37, 102, 3, 36, 13,
                5, 12, 0, 9, 0, 10, 0, 20, 0, 20,
                56, 61, 7, 10, 215, 14, 0, 56, 0, 49,
                0, 0, 17, 54, 19, 86, 64, -3, 0, 37,
                45, 0, 8, 31, 0, 20, 0, 47, 33, 0,
                49, 24, 55, 26, 21, 17, 51, 8, 80, 7,
                0, 40, 17, 0, 18, 2, 48, 6, 0, 32,
                0, 12, 4, 45, 7, 42, 46, 0, 10, 9,
                21, 0, 44, 25, 36, 41, 101, 12, 0, 0,
                0, 81, 17, 10, 0, 0, 0, 34, 9, 48,
                35, 26, 32, 0, 12, 0, 0, 22, 11, 15,
                0, 2, 47, 16, 31, 28, 79, 0, 25, 23,
                0, 55, 0, 2, 0, 0, 36, 0, 17, 15,
                24, 58, 32, 0, 5, 12, 8, 97, 0, 129,
                0, 17, 16, 17, 0, 44, 53, 150, 0, 10,
                11, 31, 0, 77, 7, 0, 0, 0, 0, 24,
                34, 21, 14, 0, 14, 35, 80, 9, 0, 6,
                78, 31, 17, 119, -1, 12, 0, 64, 39, 2,
                3, 39, 37, 47, 1, 20, 12, 33, 0, 23,
                71, 44, 0, 0, 27, 43, 4, 5, 0, 0,
                17, 18, 31, 6, 12, 0, 112, 36, 17, 22,
                10, 0, 9, 19, 0, 18, 11, 20, 0, 19,
                0, 31, 10, 89, 0, 5, 0, 34, 40, 18,
                23, 7, 11, 0, 26, 0, 37, 4, 2, 5,
                11, 0, 0, 0, 0, 1, 20, -6, 19, 3,
                0, 0, 6, 0, 0, 27, 13, 9, 0, 19,
                5, 0, 0, 9, 40, 0, -7, 0, 26, 0,
                14, 9, 9, 34, 61, 30, 35, 1, 8, 17,
                78, 39, 29, 119, 18, 50, 48, 0, 0, 0,
                0
        };
        int[] RecTD = {
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
                0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 2, 0, 0, 1, 0, 0,
                0, 0, 0, 0, 0, 1, 2, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
                0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
                0, 2, 0, 1, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
                0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 1, 0, 0, 1, 0, 2,
                0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
                1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
                0, 1, 0, 0, 2, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
                0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
                0
        };

        try (PrintWriter writer = new PrintWriter(new FileWriter("projects\\miniProj\\src\\main\\java\\apcs\\unit09\\FantasyFootball\\data.txt"))) {
            writer.println("Player\t\tPosition\t\tYards\t\tTDs");
            for (int i = 0; i < playerNames.length; i++) {
                
                writer.print(playerNames[i] + "\t\t");
                if(positions[i].equals("TE")){
                    writer.print("WR");
                }else{
                    writer.print(positions[i]);
                }
                int totalYards = passingYards[i] + rushYards[i] + RecYards[i];
                int totalTDs = passingTD[i] + rushTD[i] + RecTD[i];
                writer.print("\t\t" + totalYards + "\t\t" + totalTDs);
                writer.println();
            }
        } catch (IOException e) {
            System.out.println("An error occurred while writing to the file: " + e.getMessage());
        }
    }
}
